var countries = {
	'Kenya': "<p>Total installed electricity capacity (2010): 1,429 MW<br /> Hydro-electric: 52.1%<br /> Conventional Thermal: 32.5%<br /> Geothermal: 13.2%<br /> Wind, Others: 2.2%<br /> <br /> Total primary energy supply (2009): 18,723 ktoe<br /> Comb. Renew. and Waste: 76.0%<br /> Oil and Products: 16.5%<br /> Geothermal/solar/wind: 6.2%<br /> Hydro-electric: 1.0%<br /> Coal: 0.3%<br />",
	'Gabon': "<p>Total Installed Electricity Capacity (2010): 336 MW <br /> Hydro: 55% <br /> Thermal: 45%<br /> <br /> Total primary energy supply (2009): 1,794 ktoe<br /> Biofuels &amp; waste: 61.8% <br /> Oil and Petroleum Products:&nbsp; 25.6%<br /> Gas: 8.4%<br /> Hydro: 4.2%<br />",
	'Tanzania': "<p>Total installed electricity capacity (2011, source: Tanesco): 1,051 MW :<br /> Hydro: 58.5% <br /> Thermal: 41.5%<br /> <br /> Total primary energy supply (2009, source: IEA): 19,616 ktoe<br /> Comb. Renew. And Waste: 87.7%<br /> Petroleum Products: 8.0%<br /> Natural Gas: 2.8%<br /> Hydro-electric: 1.2%<br /> Coal: ~0.3%<br />",
	'Rwanda': "<p>Total installed electricity capacity (2009, source: MININFRA): 72.5 MW <br /> Hydroelectric: 59.1 %<br /> Thermal: 40.5%<br /> Solar: 0.4%<br /> <br /> Total primary energy supply (2007, source: GTZ): 1,610 ktoe<br /> Wood: 57%<br /> Wood for Charcoal: 23%<br /> Petroleum Products: 11%<br /> Agricultural Peat: 6%<br /> Electricity: 3%<br />",
	'Uganda': "<p>Total installed electricity capacity (2010, UETCL): 539.5 MW <br /> Thermal: 31.5%<br /> Hydroelectric: 65.4%<br /> Biomass (bagasse): 3.1%<br /> <br /> Total primary energy supply (2010): 11,080 ktoe <br /> Biomass: 92%<br /> Petroleum Products: 6%<br /> Electricity Imports: 2%<br />",
	'Burundi': "<p>Functioning installed electricity capacity (2008): 52 MW <br /> Hydro-electric: 98.08%<br /> Conventional Thermal: 1.92%<br /> <br /> Total primary energy supply (2009): <br /> Biomass: 96%<br /> Petroleum: 1.65%<br /> Electricity:&nbsp; 2.2%<br />",
	'Democratic Republic of the Congo': "<p>Total installed electricity capacity (2008): 2,475 MW<br /> Hydro-electric: 98.7%<br /> Non-renewables (Thermal etc.): 1.3%<br /> <br /> Total primary energy supply (2009): 22,921 ktoe<br /> Combustible Renewables and Waste: 93.6%<br /> Hydroelectric: 2.9%<br /> Petroleum Products: 2.4%<br /> Coal: 1.3%<br /> Natural Gas: 0.03%<br /> Crude Oil: 0.01%<br /> Electricity Exports: -0.3%<br />",
	'Ethiopia': "<p>Total installed electricity capacity (2008): 929 MW</p> <ul> <li>Hydro-electric: 84.36%</li> <li>Conventional thermal: 14.85%</li> <li>Geothermal: 0.79%</li> </ul> <p><br /> Total primary energy supply (2009): 32,678 ktoe</p> <ul> <li>Biofuels and Waste: 92.0%</li> <li>Petroleum Products: 7.1%</li> <li>Hydro-electric: 0.9%</li> </ul>",
	'Somalia': "<p>Total installed electricity capacity (2006): 80MW</p> <ul> <li>Thermal : 100%</li> </ul> <p>",
	'Malawi': "<p><b>Electricity </b><br /> Total installed electricity capacity (2008): 315 MW<br />",
}